version: '3'
services:
  store:
    image: openlink/virtuoso-opensource-7
    container_name: virtuoso
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      DBA_PASSWORD: dba
    volumes:
      - ./db:/database
      - ./data/2023/dbpedia:/tmp/dbpedia
      - ./data/2023/lmdb:/tmp/lmdb